/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAnalyticsRouteImport } from './routes/ai-analytics'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as UsersManagementRouteImport } from './routes/users-management'
import { Route as AiBreakdownSparepartRouteImport } from './routes/ai/breakdown-sparepart'
import { Route as AiForecastPartRouteImport } from './routes/ai/forecast-part'
import { Route as AiKpiRouteImport } from './routes/ai/kpi'
import { Route as AiMaintenanceRouteImport } from './routes/ai/maintenance'
import { Route as AiSparepartRouteImport } from './routes/ai/sparepart'
import { Route as ApprovalMaintenanceRouteImport } from './routes/approval/maintenance'
import { Route as ApprovalSparePartRouteImport } from './routes/approval/spare-part'
import { Route as DashboardBreakdownRouteImport } from './routes/dashboard/breakdown'
import { Route as DashboardCorrectiveRouteImport } from './routes/dashboard/corrective'
import { Route as DashboardKpiReportRouteImport } from './routes/dashboard/kpi-report'
import { Route as DashboardMachineRouteImport } from './routes/dashboard/machine'
import { Route as DashboardMachineProblemTrendRouteImport } from './routes/dashboard/machine-problem-trend'
import { Route as DashboardManpowerRouteImport } from './routes/dashboard/manpower'
import { Route as DashboardSparepartRouteImport } from './routes/dashboard/sparepart'
import { Route as DocumentationIndexRouteImport } from './routes/documentation/index'
import { Route as MasterDataDocumentNumberRouteImport } from './routes/master-data/document-number'
import { Route as MasterDataParameterRouteImport } from './routes/master-data/parameter'
import { Route as ReportMaintenanceRouteImport } from './routes/report/maintenance'
import { Route as ReportSparepartRouteImport } from './routes/report/sparepart'
import { Route as SetupWorkflowApprovalRouteImport } from './routes/setup/workflow-approval'
import { Route as SparePartInventoryRouteImport } from './routes/spare-part/inventory'
import { Route as SparePartLogPartRouteImport } from './routes/spare-part/log-part'
import { Route as SparePartPurchaseReminderRouteImport } from './routes/spare-part/purchase-reminder'
import { Route as SparePartRequestPartRouteImport } from './routes/spare-part/request-part'
import { Route as SparePartStockTransactionRouteImport } from './routes/spare-part/stock-transaction'
import { Route as WorkOrderIndexRouteImport } from './routes/work-order/index'
import { Route as WorkOrderIdRouteImport } from './routes/work-order/$id'
import { Route as WorkOrderAddRouteImport } from './routes/work-order/add'
import { Route as ApprovalMaintenanceIdRouteImport } from './routes/approval/maintenance.$id'
import { Route as DocumentationMachineIdIndexRouteImport } from './routes/documentation/$machineId/index'
import { Route as MasterDataDepartmentIndexRouteImport } from './routes/master-data/department/index'
import { Route as MasterDataDepartmentIdRouteImport } from './routes/master-data/department/$id'
import { Route as MasterDataDepartmentNewRouteImport } from './routes/master-data/department/new'
import { Route as MasterDataMachineIndexRouteImport } from './routes/master-data/machine/index'
import { Route as MasterDataMachineIdRouteImport } from './routes/master-data/machine/$id'
import { Route as MasterDataMachineNewRouteImport } from './routes/master-data/machine/new'
import { Route as MasterDataSparepartIndexRouteImport } from './routes/master-data/sparepart/index'
import { Route as MasterDataSparepartIdRouteImport } from './routes/master-data/sparepart/$id'
import { Route as MasterDataSparepartNewRouteImport } from './routes/master-data/sparepart/new'
import { Route as SparePartOrderRequestIndexRouteImport } from './routes/spare-part/order-request/index'
import { Route as SparePartOrderRequestIdRouteImport } from './routes/spare-part/order-request/$id'
import { Route as SparePartOrderRequestCreateSorRouteImport } from './routes/spare-part/order-request/create-sor'
import { Route as SparePartOrderRequestEditRouteImport } from './routes/spare-part/order-request/edit'
import { Route as SparePartRequestOrderListIndexRouteImport } from './routes/spare-part/request-order-list/index'
import { Route as SparePartRequestOrderListIdRouteImport } from './routes/spare-part/request-order-list/$id'
import { Route as SparePartRequestOrderListNewRouteImport } from './routes/spare-part/request-order-list/new'
import { Route as DocumentationMachineIdHistoryIndexRouteImport } from './routes/documentation/$machineId/history/index'
import { Route as DocumentationMachineIdHistoryHistoryIdRouteImport } from './routes/documentation/$machineId/history/$historyId'
import { Route as MasterDataSparepartWarehouseNewRouteImport } from './routes/master-data/sparepart/warehouse/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalyticsRoute = AiAnalyticsRouteImport.update({
  id: '/ai-analytics',
  path: '/ai-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersManagementRoute = UsersManagementRouteImport.update({
  id: '/users-management',
  path: '/users-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBreakdownSparepartRoute = AiBreakdownSparepartRouteImport.update({
  id: '/ai/breakdown-sparepart',
  path: '/ai/breakdown-sparepart',
  getParentRoute: () => rootRouteImport,
} as any)
const AiForecastPartRoute = AiForecastPartRouteImport.update({
  id: '/ai/forecast-part',
  path: '/ai/forecast-part',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKpiRoute = AiKpiRouteImport.update({
  id: '/ai/kpi',
  path: '/ai/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMaintenanceRoute = AiMaintenanceRouteImport.update({
  id: '/ai/maintenance',
  path: '/ai/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSparepartRoute = AiSparepartRouteImport.update({
  id: '/ai/sparepart',
  path: '/ai/sparepart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalMaintenanceRoute = ApprovalMaintenanceRouteImport.update({
  id: '/approval/maintenance',
  path: '/approval/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalSparePartRoute = ApprovalSparePartRouteImport.update({
  id: '/approval/spare-part',
  path: '/approval/spare-part',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBreakdownRoute = DashboardBreakdownRouteImport.update({
  id: '/dashboard/breakdown',
  path: '/dashboard/breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCorrectiveRoute = DashboardCorrectiveRouteImport.update({
  id: '/dashboard/corrective',
  path: '/dashboard/corrective',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardKpiReportRoute = DashboardKpiReportRouteImport.update({
  id: '/dashboard/kpi-report',
  path: '/dashboard/kpi-report',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMachineRoute = DashboardMachineRouteImport.update({
  id: '/dashboard/machine',
  path: '/dashboard/machine',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMachineProblemTrendRoute =
  DashboardMachineProblemTrendRouteImport.update({
    id: '/dashboard/machine-problem-trend',
    path: '/dashboard/machine-problem-trend',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardManpowerRoute = DashboardManpowerRouteImport.update({
  id: '/dashboard/manpower',
  path: '/dashboard/manpower',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSparepartRoute = DashboardSparepartRouteImport.update({
  id: '/dashboard/sparepart',
  path: '/dashboard/sparepart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIndexRoute = DocumentationIndexRouteImport.update({
  id: '/documentation/',
  path: '/documentation/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataDocumentNumberRoute =
  MasterDataDocumentNumberRouteImport.update({
    id: '/master-data/document-number',
    path: '/master-data/document-number',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataParameterRoute = MasterDataParameterRouteImport.update({
  id: '/master-data/parameter',
  path: '/master-data/parameter',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportMaintenanceRoute = ReportMaintenanceRouteImport.update({
  id: '/report/maintenance',
  path: '/report/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSparepartRoute = ReportSparepartRouteImport.update({
  id: '/report/sparepart',
  path: '/report/sparepart',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupWorkflowApprovalRoute = SetupWorkflowApprovalRouteImport.update({
  id: '/setup/workflow-approval',
  path: '/setup/workflow-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartInventoryRoute = SparePartInventoryRouteImport.update({
  id: '/spare-part/inventory',
  path: '/spare-part/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartLogPartRoute = SparePartLogPartRouteImport.update({
  id: '/spare-part/log-part',
  path: '/spare-part/log-part',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartPurchaseReminderRoute =
  SparePartPurchaseReminderRouteImport.update({
    id: '/spare-part/purchase-reminder',
    path: '/spare-part/purchase-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const SparePartRequestPartRoute = SparePartRequestPartRouteImport.update({
  id: '/spare-part/request-part',
  path: '/spare-part/request-part',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartStockTransactionRoute =
  SparePartStockTransactionRouteImport.update({
    id: '/spare-part/stock-transaction',
    path: '/spare-part/stock-transaction',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkOrderIndexRoute = WorkOrderIndexRouteImport.update({
  id: '/work-order/',
  path: '/work-order/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrderIdRoute = WorkOrderIdRouteImport.update({
  id: '/work-order/$id',
  path: '/work-order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrderAddRoute = WorkOrderAddRouteImport.update({
  id: '/work-order/add',
  path: '/work-order/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalMaintenanceIdRoute = ApprovalMaintenanceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApprovalMaintenanceRoute,
} as any)
const DocumentationMachineIdIndexRoute =
  DocumentationMachineIdIndexRouteImport.update({
    id: '/documentation/$machineId/',
    path: '/documentation/$machineId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataDepartmentIndexRoute =
  MasterDataDepartmentIndexRouteImport.update({
    id: '/master-data/department/',
    path: '/master-data/department/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataDepartmentIdRoute = MasterDataDepartmentIdRouteImport.update({
  id: '/master-data/department/$id',
  path: '/master-data/department/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataDepartmentNewRoute = MasterDataDepartmentNewRouteImport.update({
  id: '/master-data/department/new',
  path: '/master-data/department/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataMachineIndexRoute = MasterDataMachineIndexRouteImport.update({
  id: '/master-data/machine/',
  path: '/master-data/machine/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataMachineIdRoute = MasterDataMachineIdRouteImport.update({
  id: '/master-data/machine/$id',
  path: '/master-data/machine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataMachineNewRoute = MasterDataMachineNewRouteImport.update({
  id: '/master-data/machine/new',
  path: '/master-data/machine/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataSparepartIndexRoute =
  MasterDataSparepartIndexRouteImport.update({
    id: '/master-data/sparepart/',
    path: '/master-data/sparepart/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataSparepartIdRoute = MasterDataSparepartIdRouteImport.update({
  id: '/master-data/sparepart/$id',
  path: '/master-data/sparepart/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataSparepartNewRoute = MasterDataSparepartNewRouteImport.update({
  id: '/master-data/sparepart/new',
  path: '/master-data/sparepart/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartOrderRequestIndexRoute =
  SparePartOrderRequestIndexRouteImport.update({
    id: '/spare-part/order-request/',
    path: '/spare-part/order-request/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SparePartOrderRequestIdRoute = SparePartOrderRequestIdRouteImport.update({
  id: '/spare-part/order-request/$id',
  path: '/spare-part/order-request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartOrderRequestCreateSorRoute =
  SparePartOrderRequestCreateSorRouteImport.update({
    id: '/spare-part/order-request/create-sor',
    path: '/spare-part/order-request/create-sor',
    getParentRoute: () => rootRouteImport,
  } as any)
const SparePartOrderRequestEditRoute =
  SparePartOrderRequestEditRouteImport.update({
    id: '/spare-part/order-request/edit',
    path: '/spare-part/order-request/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const SparePartRequestOrderListIndexRoute =
  SparePartRequestOrderListIndexRouteImport.update({
    id: '/spare-part/request-order-list/',
    path: '/spare-part/request-order-list/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SparePartRequestOrderListIdRoute =
  SparePartRequestOrderListIdRouteImport.update({
    id: '/spare-part/request-order-list/$id',
    path: '/spare-part/request-order-list/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const SparePartRequestOrderListNewRoute =
  SparePartRequestOrderListNewRouteImport.update({
    id: '/spare-part/request-order-list/new',
    path: '/spare-part/request-order-list/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentationMachineIdHistoryIndexRoute =
  DocumentationMachineIdHistoryIndexRouteImport.update({
    id: '/documentation/$machineId/history/',
    path: '/documentation/$machineId/history/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentationMachineIdHistoryHistoryIdRoute =
  DocumentationMachineIdHistoryHistoryIdRouteImport.update({
    id: '/documentation/$machineId/history/$historyId',
    path: '/documentation/$machineId/history/$historyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataSparepartWarehouseNewRoute =
  MasterDataSparepartWarehouseNewRouteImport.update({
    id: '/master-data/sparepart/warehouse/new',
    path: '/master-data/sparepart/warehouse/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analytics': typeof AiAnalyticsRoute
  '/checklist': typeof ChecklistRoute
  '/schedule': typeof ScheduleRoute
  '/users-management': typeof UsersManagementRoute
  '/ai/breakdown-sparepart': typeof AiBreakdownSparepartRoute
  '/ai/forecast-part': typeof AiForecastPartRoute
  '/ai/kpi': typeof AiKpiRoute
  '/ai/maintenance': typeof AiMaintenanceRoute
  '/ai/sparepart': typeof AiSparepartRoute
  '/approval/maintenance': typeof ApprovalMaintenanceRouteWithChildren
  '/approval/spare-part': typeof ApprovalSparePartRoute
  '/dashboard/breakdown': typeof DashboardBreakdownRoute
  '/dashboard/corrective': typeof DashboardCorrectiveRoute
  '/dashboard/kpi-report': typeof DashboardKpiReportRoute
  '/dashboard/machine': typeof DashboardMachineRoute
  '/dashboard/machine-problem-trend': typeof DashboardMachineProblemTrendRoute
  '/dashboard/manpower': typeof DashboardManpowerRoute
  '/dashboard/sparepart': typeof DashboardSparepartRoute
  '/master-data/document-number': typeof MasterDataDocumentNumberRoute
  '/master-data/parameter': typeof MasterDataParameterRoute
  '/report/maintenance': typeof ReportMaintenanceRoute
  '/report/sparepart': typeof ReportSparepartRoute
  '/setup/workflow-approval': typeof SetupWorkflowApprovalRoute
  '/spare-part/inventory': typeof SparePartInventoryRoute
  '/spare-part/log-part': typeof SparePartLogPartRoute
  '/spare-part/purchase-reminder': typeof SparePartPurchaseReminderRoute
  '/spare-part/request-part': typeof SparePartRequestPartRoute
  '/spare-part/stock-transaction': typeof SparePartStockTransactionRoute
  '/work-order/$id': typeof WorkOrderIdRoute
  '/work-order/add': typeof WorkOrderAddRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/work-order/': typeof WorkOrderIndexRoute
  '/approval/maintenance/$id': typeof ApprovalMaintenanceIdRoute
  '/master-data/department/$id': typeof MasterDataDepartmentIdRoute
  '/master-data/department/new': typeof MasterDataDepartmentNewRoute
  '/master-data/machine/$id': typeof MasterDataMachineIdRoute
  '/master-data/machine/new': typeof MasterDataMachineNewRoute
  '/master-data/sparepart/$id': typeof MasterDataSparepartIdRoute
  '/master-data/sparepart/new': typeof MasterDataSparepartNewRoute
  '/spare-part/order-request/$id': typeof SparePartOrderRequestIdRoute
  '/spare-part/order-request/create-sor': typeof SparePartOrderRequestCreateSorRoute
  '/spare-part/order-request/edit': typeof SparePartOrderRequestEditRoute
  '/spare-part/request-order-list/$id': typeof SparePartRequestOrderListIdRoute
  '/spare-part/request-order-list/new': typeof SparePartRequestOrderListNewRoute
  '/documentation/$machineId/': typeof DocumentationMachineIdIndexRoute
  '/master-data/department/': typeof MasterDataDepartmentIndexRoute
  '/master-data/machine/': typeof MasterDataMachineIndexRoute
  '/master-data/sparepart/': typeof MasterDataSparepartIndexRoute
  '/spare-part/order-request/': typeof SparePartOrderRequestIndexRoute
  '/spare-part/request-order-list/': typeof SparePartRequestOrderListIndexRoute
  '/documentation/$machineId/history/$historyId': typeof DocumentationMachineIdHistoryHistoryIdRoute
  '/master-data/sparepart/warehouse/new': typeof MasterDataSparepartWarehouseNewRoute
  '/documentation/$machineId/history/': typeof DocumentationMachineIdHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analytics': typeof AiAnalyticsRoute
  '/checklist': typeof ChecklistRoute
  '/schedule': typeof ScheduleRoute
  '/users-management': typeof UsersManagementRoute
  '/ai/breakdown-sparepart': typeof AiBreakdownSparepartRoute
  '/ai/forecast-part': typeof AiForecastPartRoute
  '/ai/kpi': typeof AiKpiRoute
  '/ai/maintenance': typeof AiMaintenanceRoute
  '/ai/sparepart': typeof AiSparepartRoute
  '/approval/maintenance': typeof ApprovalMaintenanceRouteWithChildren
  '/approval/spare-part': typeof ApprovalSparePartRoute
  '/dashboard/breakdown': typeof DashboardBreakdownRoute
  '/dashboard/corrective': typeof DashboardCorrectiveRoute
  '/dashboard/kpi-report': typeof DashboardKpiReportRoute
  '/dashboard/machine': typeof DashboardMachineRoute
  '/dashboard/machine-problem-trend': typeof DashboardMachineProblemTrendRoute
  '/dashboard/manpower': typeof DashboardManpowerRoute
  '/dashboard/sparepart': typeof DashboardSparepartRoute
  '/master-data/document-number': typeof MasterDataDocumentNumberRoute
  '/master-data/parameter': typeof MasterDataParameterRoute
  '/report/maintenance': typeof ReportMaintenanceRoute
  '/report/sparepart': typeof ReportSparepartRoute
  '/setup/workflow-approval': typeof SetupWorkflowApprovalRoute
  '/spare-part/inventory': typeof SparePartInventoryRoute
  '/spare-part/log-part': typeof SparePartLogPartRoute
  '/spare-part/purchase-reminder': typeof SparePartPurchaseReminderRoute
  '/spare-part/request-part': typeof SparePartRequestPartRoute
  '/spare-part/stock-transaction': typeof SparePartStockTransactionRoute
  '/work-order/$id': typeof WorkOrderIdRoute
  '/work-order/add': typeof WorkOrderAddRoute
  '/documentation': typeof DocumentationIndexRoute
  '/work-order': typeof WorkOrderIndexRoute
  '/approval/maintenance/$id': typeof ApprovalMaintenanceIdRoute
  '/master-data/department/$id': typeof MasterDataDepartmentIdRoute
  '/master-data/department/new': typeof MasterDataDepartmentNewRoute
  '/master-data/machine/$id': typeof MasterDataMachineIdRoute
  '/master-data/machine/new': typeof MasterDataMachineNewRoute
  '/master-data/sparepart/$id': typeof MasterDataSparepartIdRoute
  '/master-data/sparepart/new': typeof MasterDataSparepartNewRoute
  '/spare-part/order-request/$id': typeof SparePartOrderRequestIdRoute
  '/spare-part/order-request/create-sor': typeof SparePartOrderRequestCreateSorRoute
  '/spare-part/order-request/edit': typeof SparePartOrderRequestEditRoute
  '/spare-part/request-order-list/$id': typeof SparePartRequestOrderListIdRoute
  '/spare-part/request-order-list/new': typeof SparePartRequestOrderListNewRoute
  '/documentation/$machineId': typeof DocumentationMachineIdIndexRoute
  '/master-data/department': typeof MasterDataDepartmentIndexRoute
  '/master-data/machine': typeof MasterDataMachineIndexRoute
  '/master-data/sparepart': typeof MasterDataSparepartIndexRoute
  '/spare-part/order-request': typeof SparePartOrderRequestIndexRoute
  '/spare-part/request-order-list': typeof SparePartRequestOrderListIndexRoute
  '/documentation/$machineId/history/$historyId': typeof DocumentationMachineIdHistoryHistoryIdRoute
  '/master-data/sparepart/warehouse/new': typeof MasterDataSparepartWarehouseNewRoute
  '/documentation/$machineId/history': typeof DocumentationMachineIdHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analytics': typeof AiAnalyticsRoute
  '/checklist': typeof ChecklistRoute
  '/schedule': typeof ScheduleRoute
  '/users-management': typeof UsersManagementRoute
  '/ai/breakdown-sparepart': typeof AiBreakdownSparepartRoute
  '/ai/forecast-part': typeof AiForecastPartRoute
  '/ai/kpi': typeof AiKpiRoute
  '/ai/maintenance': typeof AiMaintenanceRoute
  '/ai/sparepart': typeof AiSparepartRoute
  '/approval/maintenance': typeof ApprovalMaintenanceRouteWithChildren
  '/approval/spare-part': typeof ApprovalSparePartRoute
  '/dashboard/breakdown': typeof DashboardBreakdownRoute
  '/dashboard/corrective': typeof DashboardCorrectiveRoute
  '/dashboard/kpi-report': typeof DashboardKpiReportRoute
  '/dashboard/machine': typeof DashboardMachineRoute
  '/dashboard/machine-problem-trend': typeof DashboardMachineProblemTrendRoute
  '/dashboard/manpower': typeof DashboardManpowerRoute
  '/dashboard/sparepart': typeof DashboardSparepartRoute
  '/master-data/document-number': typeof MasterDataDocumentNumberRoute
  '/master-data/parameter': typeof MasterDataParameterRoute
  '/report/maintenance': typeof ReportMaintenanceRoute
  '/report/sparepart': typeof ReportSparepartRoute
  '/setup/workflow-approval': typeof SetupWorkflowApprovalRoute
  '/spare-part/inventory': typeof SparePartInventoryRoute
  '/spare-part/log-part': typeof SparePartLogPartRoute
  '/spare-part/purchase-reminder': typeof SparePartPurchaseReminderRoute
  '/spare-part/request-part': typeof SparePartRequestPartRoute
  '/spare-part/stock-transaction': typeof SparePartStockTransactionRoute
  '/work-order/$id': typeof WorkOrderIdRoute
  '/work-order/add': typeof WorkOrderAddRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/work-order/': typeof WorkOrderIndexRoute
  '/approval/maintenance/$id': typeof ApprovalMaintenanceIdRoute
  '/master-data/department/$id': typeof MasterDataDepartmentIdRoute
  '/master-data/department/new': typeof MasterDataDepartmentNewRoute
  '/master-data/machine/$id': typeof MasterDataMachineIdRoute
  '/master-data/machine/new': typeof MasterDataMachineNewRoute
  '/master-data/sparepart/$id': typeof MasterDataSparepartIdRoute
  '/master-data/sparepart/new': typeof MasterDataSparepartNewRoute
  '/spare-part/order-request/$id': typeof SparePartOrderRequestIdRoute
  '/spare-part/order-request/create-sor': typeof SparePartOrderRequestCreateSorRoute
  '/spare-part/order-request/edit': typeof SparePartOrderRequestEditRoute
  '/spare-part/request-order-list/$id': typeof SparePartRequestOrderListIdRoute
  '/spare-part/request-order-list/new': typeof SparePartRequestOrderListNewRoute
  '/documentation/$machineId/': typeof DocumentationMachineIdIndexRoute
  '/master-data/department/': typeof MasterDataDepartmentIndexRoute
  '/master-data/machine/': typeof MasterDataMachineIndexRoute
  '/master-data/sparepart/': typeof MasterDataSparepartIndexRoute
  '/spare-part/order-request/': typeof SparePartOrderRequestIndexRoute
  '/spare-part/request-order-list/': typeof SparePartRequestOrderListIndexRoute
  '/documentation/$machineId/history/$historyId': typeof DocumentationMachineIdHistoryHistoryIdRoute
  '/master-data/sparepart/warehouse/new': typeof MasterDataSparepartWarehouseNewRoute
  '/documentation/$machineId/history/': typeof DocumentationMachineIdHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analytics'
    | '/checklist'
    | '/schedule'
    | '/users-management'
    | '/ai/breakdown-sparepart'
    | '/ai/forecast-part'
    | '/ai/kpi'
    | '/ai/maintenance'
    | '/ai/sparepart'
    | '/approval/maintenance'
    | '/approval/spare-part'
    | '/dashboard/breakdown'
    | '/dashboard/corrective'
    | '/dashboard/kpi-report'
    | '/dashboard/machine'
    | '/dashboard/machine-problem-trend'
    | '/dashboard/manpower'
    | '/dashboard/sparepart'
    | '/master-data/document-number'
    | '/master-data/parameter'
    | '/report/maintenance'
    | '/report/sparepart'
    | '/setup/workflow-approval'
    | '/spare-part/inventory'
    | '/spare-part/log-part'
    | '/spare-part/purchase-reminder'
    | '/spare-part/request-part'
    | '/spare-part/stock-transaction'
    | '/work-order/$id'
    | '/work-order/add'
    | '/documentation/'
    | '/work-order/'
    | '/approval/maintenance/$id'
    | '/master-data/department/$id'
    | '/master-data/department/new'
    | '/master-data/machine/$id'
    | '/master-data/machine/new'
    | '/master-data/sparepart/$id'
    | '/master-data/sparepart/new'
    | '/spare-part/order-request/$id'
    | '/spare-part/order-request/create-sor'
    | '/spare-part/order-request/edit'
    | '/spare-part/request-order-list/$id'
    | '/spare-part/request-order-list/new'
    | '/documentation/$machineId/'
    | '/master-data/department/'
    | '/master-data/machine/'
    | '/master-data/sparepart/'
    | '/spare-part/order-request/'
    | '/spare-part/request-order-list/'
    | '/documentation/$machineId/history/$historyId'
    | '/master-data/sparepart/warehouse/new'
    | '/documentation/$machineId/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analytics'
    | '/checklist'
    | '/schedule'
    | '/users-management'
    | '/ai/breakdown-sparepart'
    | '/ai/forecast-part'
    | '/ai/kpi'
    | '/ai/maintenance'
    | '/ai/sparepart'
    | '/approval/maintenance'
    | '/approval/spare-part'
    | '/dashboard/breakdown'
    | '/dashboard/corrective'
    | '/dashboard/kpi-report'
    | '/dashboard/machine'
    | '/dashboard/machine-problem-trend'
    | '/dashboard/manpower'
    | '/dashboard/sparepart'
    | '/master-data/document-number'
    | '/master-data/parameter'
    | '/report/maintenance'
    | '/report/sparepart'
    | '/setup/workflow-approval'
    | '/spare-part/inventory'
    | '/spare-part/log-part'
    | '/spare-part/purchase-reminder'
    | '/spare-part/request-part'
    | '/spare-part/stock-transaction'
    | '/work-order/$id'
    | '/work-order/add'
    | '/documentation'
    | '/work-order'
    | '/approval/maintenance/$id'
    | '/master-data/department/$id'
    | '/master-data/department/new'
    | '/master-data/machine/$id'
    | '/master-data/machine/new'
    | '/master-data/sparepart/$id'
    | '/master-data/sparepart/new'
    | '/spare-part/order-request/$id'
    | '/spare-part/order-request/create-sor'
    | '/spare-part/order-request/edit'
    | '/spare-part/request-order-list/$id'
    | '/spare-part/request-order-list/new'
    | '/documentation/$machineId'
    | '/master-data/department'
    | '/master-data/machine'
    | '/master-data/sparepart'
    | '/spare-part/order-request'
    | '/spare-part/request-order-list'
    | '/documentation/$machineId/history/$historyId'
    | '/master-data/sparepart/warehouse/new'
    | '/documentation/$machineId/history'
  id:
    | '__root__'
    | '/'
    | '/ai-analytics'
    | '/checklist'
    | '/schedule'
    | '/users-management'
    | '/ai/breakdown-sparepart'
    | '/ai/forecast-part'
    | '/ai/kpi'
    | '/ai/maintenance'
    | '/ai/sparepart'
    | '/approval/maintenance'
    | '/approval/spare-part'
    | '/dashboard/breakdown'
    | '/dashboard/corrective'
    | '/dashboard/kpi-report'
    | '/dashboard/machine'
    | '/dashboard/machine-problem-trend'
    | '/dashboard/manpower'
    | '/dashboard/sparepart'
    | '/master-data/document-number'
    | '/master-data/parameter'
    | '/report/maintenance'
    | '/report/sparepart'
    | '/setup/workflow-approval'
    | '/spare-part/inventory'
    | '/spare-part/log-part'
    | '/spare-part/purchase-reminder'
    | '/spare-part/request-part'
    | '/spare-part/stock-transaction'
    | '/work-order/$id'
    | '/work-order/add'
    | '/documentation/'
    | '/work-order/'
    | '/approval/maintenance/$id'
    | '/master-data/department/$id'
    | '/master-data/department/new'
    | '/master-data/machine/$id'
    | '/master-data/machine/new'
    | '/master-data/sparepart/$id'
    | '/master-data/sparepart/new'
    | '/spare-part/order-request/$id'
    | '/spare-part/order-request/create-sor'
    | '/spare-part/order-request/edit'
    | '/spare-part/request-order-list/$id'
    | '/spare-part/request-order-list/new'
    | '/documentation/$machineId/'
    | '/master-data/department/'
    | '/master-data/machine/'
    | '/master-data/sparepart/'
    | '/spare-part/order-request/'
    | '/spare-part/request-order-list/'
    | '/documentation/$machineId/history/$historyId'
    | '/master-data/sparepart/warehouse/new'
    | '/documentation/$machineId/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalyticsRoute: typeof AiAnalyticsRoute
  ChecklistRoute: typeof ChecklistRoute
  ScheduleRoute: typeof ScheduleRoute
  UsersManagementRoute: typeof UsersManagementRoute
  AiBreakdownSparepartRoute: typeof AiBreakdownSparepartRoute
  AiForecastPartRoute: typeof AiForecastPartRoute
  AiKpiRoute: typeof AiKpiRoute
  AiMaintenanceRoute: typeof AiMaintenanceRoute
  AiSparepartRoute: typeof AiSparepartRoute
  ApprovalMaintenanceRoute: typeof ApprovalMaintenanceRouteWithChildren
  ApprovalSparePartRoute: typeof ApprovalSparePartRoute
  DashboardBreakdownRoute: typeof DashboardBreakdownRoute
  DashboardCorrectiveRoute: typeof DashboardCorrectiveRoute
  DashboardKpiReportRoute: typeof DashboardKpiReportRoute
  DashboardMachineRoute: typeof DashboardMachineRoute
  DashboardMachineProblemTrendRoute: typeof DashboardMachineProblemTrendRoute
  DashboardManpowerRoute: typeof DashboardManpowerRoute
  DashboardSparepartRoute: typeof DashboardSparepartRoute
  MasterDataDocumentNumberRoute: typeof MasterDataDocumentNumberRoute
  MasterDataParameterRoute: typeof MasterDataParameterRoute
  ReportMaintenanceRoute: typeof ReportMaintenanceRoute
  ReportSparepartRoute: typeof ReportSparepartRoute
  SetupWorkflowApprovalRoute: typeof SetupWorkflowApprovalRoute
  SparePartInventoryRoute: typeof SparePartInventoryRoute
  SparePartLogPartRoute: typeof SparePartLogPartRoute
  SparePartPurchaseReminderRoute: typeof SparePartPurchaseReminderRoute
  SparePartRequestPartRoute: typeof SparePartRequestPartRoute
  SparePartStockTransactionRoute: typeof SparePartStockTransactionRoute
  WorkOrderIdRoute: typeof WorkOrderIdRoute
  WorkOrderAddRoute: typeof WorkOrderAddRoute
  DocumentationIndexRoute: typeof DocumentationIndexRoute
  WorkOrderIndexRoute: typeof WorkOrderIndexRoute
  MasterDataDepartmentIdRoute: typeof MasterDataDepartmentIdRoute
  MasterDataDepartmentNewRoute: typeof MasterDataDepartmentNewRoute
  MasterDataMachineIdRoute: typeof MasterDataMachineIdRoute
  MasterDataMachineNewRoute: typeof MasterDataMachineNewRoute
  MasterDataSparepartIdRoute: typeof MasterDataSparepartIdRoute
  MasterDataSparepartNewRoute: typeof MasterDataSparepartNewRoute
  SparePartOrderRequestIdRoute: typeof SparePartOrderRequestIdRoute
  SparePartOrderRequestCreateSorRoute: typeof SparePartOrderRequestCreateSorRoute
  SparePartOrderRequestEditRoute: typeof SparePartOrderRequestEditRoute
  SparePartRequestOrderListIdRoute: typeof SparePartRequestOrderListIdRoute
  SparePartRequestOrderListNewRoute: typeof SparePartRequestOrderListNewRoute
  DocumentationMachineIdIndexRoute: typeof DocumentationMachineIdIndexRoute
  MasterDataDepartmentIndexRoute: typeof MasterDataDepartmentIndexRoute
  MasterDataMachineIndexRoute: typeof MasterDataMachineIndexRoute
  MasterDataSparepartIndexRoute: typeof MasterDataSparepartIndexRoute
  SparePartOrderRequestIndexRoute: typeof SparePartOrderRequestIndexRoute
  SparePartRequestOrderListIndexRoute: typeof SparePartRequestOrderListIndexRoute
  DocumentationMachineIdHistoryHistoryIdRoute: typeof DocumentationMachineIdHistoryHistoryIdRoute
  MasterDataSparepartWarehouseNewRoute: typeof MasterDataSparepartWarehouseNewRoute
  DocumentationMachineIdHistoryIndexRoute: typeof DocumentationMachineIdHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analytics': {
      id: '/ai-analytics'
      path: '/ai-analytics'
      fullPath: '/ai-analytics'
      preLoaderRoute: typeof AiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users-management': {
      id: '/users-management'
      path: '/users-management'
      fullPath: '/users-management'
      preLoaderRoute: typeof UsersManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/breakdown-sparepart': {
      id: '/ai/breakdown-sparepart'
      path: '/ai/breakdown-sparepart'
      fullPath: '/ai/breakdown-sparepart'
      preLoaderRoute: typeof AiBreakdownSparepartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/forecast-part': {
      id: '/ai/forecast-part'
      path: '/ai/forecast-part'
      fullPath: '/ai/forecast-part'
      preLoaderRoute: typeof AiForecastPartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/kpi': {
      id: '/ai/kpi'
      path: '/ai/kpi'
      fullPath: '/ai/kpi'
      preLoaderRoute: typeof AiKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/maintenance': {
      id: '/ai/maintenance'
      path: '/ai/maintenance'
      fullPath: '/ai/maintenance'
      preLoaderRoute: typeof AiMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/sparepart': {
      id: '/ai/sparepart'
      path: '/ai/sparepart'
      fullPath: '/ai/sparepart'
      preLoaderRoute: typeof AiSparepartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval/maintenance': {
      id: '/approval/maintenance'
      path: '/approval/maintenance'
      fullPath: '/approval/maintenance'
      preLoaderRoute: typeof ApprovalMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval/spare-part': {
      id: '/approval/spare-part'
      path: '/approval/spare-part'
      fullPath: '/approval/spare-part'
      preLoaderRoute: typeof ApprovalSparePartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/breakdown': {
      id: '/dashboard/breakdown'
      path: '/dashboard/breakdown'
      fullPath: '/dashboard/breakdown'
      preLoaderRoute: typeof DashboardBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/corrective': {
      id: '/dashboard/corrective'
      path: '/dashboard/corrective'
      fullPath: '/dashboard/corrective'
      preLoaderRoute: typeof DashboardCorrectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/kpi-report': {
      id: '/dashboard/kpi-report'
      path: '/dashboard/kpi-report'
      fullPath: '/dashboard/kpi-report'
      preLoaderRoute: typeof DashboardKpiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/machine': {
      id: '/dashboard/machine'
      path: '/dashboard/machine'
      fullPath: '/dashboard/machine'
      preLoaderRoute: typeof DashboardMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/machine-problem-trend': {
      id: '/dashboard/machine-problem-trend'
      path: '/dashboard/machine-problem-trend'
      fullPath: '/dashboard/machine-problem-trend'
      preLoaderRoute: typeof DashboardMachineProblemTrendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manpower': {
      id: '/dashboard/manpower'
      path: '/dashboard/manpower'
      fullPath: '/dashboard/manpower'
      preLoaderRoute: typeof DashboardManpowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sparepart': {
      id: '/dashboard/sparepart'
      path: '/dashboard/sparepart'
      fullPath: '/dashboard/sparepart'
      preLoaderRoute: typeof DashboardSparepartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/documentation'
      fullPath: '/documentation/'
      preLoaderRoute: typeof DocumentationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/document-number': {
      id: '/master-data/document-number'
      path: '/master-data/document-number'
      fullPath: '/master-data/document-number'
      preLoaderRoute: typeof MasterDataDocumentNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/parameter': {
      id: '/master-data/parameter'
      path: '/master-data/parameter'
      fullPath: '/master-data/parameter'
      preLoaderRoute: typeof MasterDataParameterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/maintenance': {
      id: '/report/maintenance'
      path: '/report/maintenance'
      fullPath: '/report/maintenance'
      preLoaderRoute: typeof ReportMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/sparepart': {
      id: '/report/sparepart'
      path: '/report/sparepart'
      fullPath: '/report/sparepart'
      preLoaderRoute: typeof ReportSparepartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/workflow-approval': {
      id: '/setup/workflow-approval'
      path: '/setup/workflow-approval'
      fullPath: '/setup/workflow-approval'
      preLoaderRoute: typeof SetupWorkflowApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/inventory': {
      id: '/spare-part/inventory'
      path: '/spare-part/inventory'
      fullPath: '/spare-part/inventory'
      preLoaderRoute: typeof SparePartInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/log-part': {
      id: '/spare-part/log-part'
      path: '/spare-part/log-part'
      fullPath: '/spare-part/log-part'
      preLoaderRoute: typeof SparePartLogPartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/purchase-reminder': {
      id: '/spare-part/purchase-reminder'
      path: '/spare-part/purchase-reminder'
      fullPath: '/spare-part/purchase-reminder'
      preLoaderRoute: typeof SparePartPurchaseReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/request-part': {
      id: '/spare-part/request-part'
      path: '/spare-part/request-part'
      fullPath: '/spare-part/request-part'
      preLoaderRoute: typeof SparePartRequestPartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/stock-transaction': {
      id: '/spare-part/stock-transaction'
      path: '/spare-part/stock-transaction'
      fullPath: '/spare-part/stock-transaction'
      preLoaderRoute: typeof SparePartStockTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-order/': {
      id: '/work-order/'
      path: '/work-order'
      fullPath: '/work-order/'
      preLoaderRoute: typeof WorkOrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-order/$id': {
      id: '/work-order/$id'
      path: '/work-order/$id'
      fullPath: '/work-order/$id'
      preLoaderRoute: typeof WorkOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-order/add': {
      id: '/work-order/add'
      path: '/work-order/add'
      fullPath: '/work-order/add'
      preLoaderRoute: typeof WorkOrderAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval/maintenance/$id': {
      id: '/approval/maintenance/$id'
      path: '/$id'
      fullPath: '/approval/maintenance/$id'
      preLoaderRoute: typeof ApprovalMaintenanceIdRouteImport
      parentRoute: typeof ApprovalMaintenanceRoute
    }
    '/documentation/$machineId/': {
      id: '/documentation/$machineId/'
      path: '/documentation/$machineId'
      fullPath: '/documentation/$machineId/'
      preLoaderRoute: typeof DocumentationMachineIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/department/': {
      id: '/master-data/department/'
      path: '/master-data/department'
      fullPath: '/master-data/department/'
      preLoaderRoute: typeof MasterDataDepartmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/department/$id': {
      id: '/master-data/department/$id'
      path: '/master-data/department/$id'
      fullPath: '/master-data/department/$id'
      preLoaderRoute: typeof MasterDataDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/department/new': {
      id: '/master-data/department/new'
      path: '/master-data/department/new'
      fullPath: '/master-data/department/new'
      preLoaderRoute: typeof MasterDataDepartmentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/machine/': {
      id: '/master-data/machine/'
      path: '/master-data/machine'
      fullPath: '/master-data/machine/'
      preLoaderRoute: typeof MasterDataMachineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/machine/$id': {
      id: '/master-data/machine/$id'
      path: '/master-data/machine/$id'
      fullPath: '/master-data/machine/$id'
      preLoaderRoute: typeof MasterDataMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/machine/new': {
      id: '/master-data/machine/new'
      path: '/master-data/machine/new'
      fullPath: '/master-data/machine/new'
      preLoaderRoute: typeof MasterDataMachineNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/sparepart/': {
      id: '/master-data/sparepart/'
      path: '/master-data/sparepart'
      fullPath: '/master-data/sparepart/'
      preLoaderRoute: typeof MasterDataSparepartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/sparepart/$id': {
      id: '/master-data/sparepart/$id'
      path: '/master-data/sparepart/$id'
      fullPath: '/master-data/sparepart/$id'
      preLoaderRoute: typeof MasterDataSparepartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/sparepart/new': {
      id: '/master-data/sparepart/new'
      path: '/master-data/sparepart/new'
      fullPath: '/master-data/sparepart/new'
      preLoaderRoute: typeof MasterDataSparepartNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/order-request/': {
      id: '/spare-part/order-request/'
      path: '/spare-part/order-request'
      fullPath: '/spare-part/order-request/'
      preLoaderRoute: typeof SparePartOrderRequestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/order-request/$id': {
      id: '/spare-part/order-request/$id'
      path: '/spare-part/order-request/$id'
      fullPath: '/spare-part/order-request/$id'
      preLoaderRoute: typeof SparePartOrderRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/order-request/create-sor': {
      id: '/spare-part/order-request/create-sor'
      path: '/spare-part/order-request/create-sor'
      fullPath: '/spare-part/order-request/create-sor'
      preLoaderRoute: typeof SparePartOrderRequestCreateSorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/order-request/edit': {
      id: '/spare-part/order-request/edit'
      path: '/spare-part/order-request/edit'
      fullPath: '/spare-part/order-request/edit'
      preLoaderRoute: typeof SparePartOrderRequestEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/request-order-list/': {
      id: '/spare-part/request-order-list/'
      path: '/spare-part/request-order-list'
      fullPath: '/spare-part/request-order-list/'
      preLoaderRoute: typeof SparePartRequestOrderListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/request-order-list/$id': {
      id: '/spare-part/request-order-list/$id'
      path: '/spare-part/request-order-list/$id'
      fullPath: '/spare-part/request-order-list/$id'
      preLoaderRoute: typeof SparePartRequestOrderListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-part/request-order-list/new': {
      id: '/spare-part/request-order-list/new'
      path: '/spare-part/request-order-list/new'
      fullPath: '/spare-part/request-order-list/new'
      preLoaderRoute: typeof SparePartRequestOrderListNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/$machineId/history/': {
      id: '/documentation/$machineId/history/'
      path: '/documentation/$machineId/history'
      fullPath: '/documentation/$machineId/history/'
      preLoaderRoute: typeof DocumentationMachineIdHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/$machineId/history/$historyId': {
      id: '/documentation/$machineId/history/$historyId'
      path: '/documentation/$machineId/history/$historyId'
      fullPath: '/documentation/$machineId/history/$historyId'
      preLoaderRoute: typeof DocumentationMachineIdHistoryHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/sparepart/warehouse/new': {
      id: '/master-data/sparepart/warehouse/new'
      path: '/master-data/sparepart/warehouse/new'
      fullPath: '/master-data/sparepart/warehouse/new'
      preLoaderRoute: typeof MasterDataSparepartWarehouseNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApprovalMaintenanceRouteChildren {
  ApprovalMaintenanceIdRoute: typeof ApprovalMaintenanceIdRoute
}

const ApprovalMaintenanceRouteChildren: ApprovalMaintenanceRouteChildren = {
  ApprovalMaintenanceIdRoute: ApprovalMaintenanceIdRoute,
}

const ApprovalMaintenanceRouteWithChildren =
  ApprovalMaintenanceRoute._addFileChildren(ApprovalMaintenanceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalyticsRoute: AiAnalyticsRoute,
  ChecklistRoute: ChecklistRoute,
  ScheduleRoute: ScheduleRoute,
  UsersManagementRoute: UsersManagementRoute,
  AiBreakdownSparepartRoute: AiBreakdownSparepartRoute,
  AiForecastPartRoute: AiForecastPartRoute,
  AiKpiRoute: AiKpiRoute,
  AiMaintenanceRoute: AiMaintenanceRoute,
  AiSparepartRoute: AiSparepartRoute,
  ApprovalMaintenanceRoute: ApprovalMaintenanceRouteWithChildren,
  ApprovalSparePartRoute: ApprovalSparePartRoute,
  DashboardBreakdownRoute: DashboardBreakdownRoute,
  DashboardCorrectiveRoute: DashboardCorrectiveRoute,
  DashboardKpiReportRoute: DashboardKpiReportRoute,
  DashboardMachineRoute: DashboardMachineRoute,
  DashboardMachineProblemTrendRoute: DashboardMachineProblemTrendRoute,
  DashboardManpowerRoute: DashboardManpowerRoute,
  DashboardSparepartRoute: DashboardSparepartRoute,
  MasterDataDocumentNumberRoute: MasterDataDocumentNumberRoute,
  MasterDataParameterRoute: MasterDataParameterRoute,
  ReportMaintenanceRoute: ReportMaintenanceRoute,
  ReportSparepartRoute: ReportSparepartRoute,
  SetupWorkflowApprovalRoute: SetupWorkflowApprovalRoute,
  SparePartInventoryRoute: SparePartInventoryRoute,
  SparePartLogPartRoute: SparePartLogPartRoute,
  SparePartPurchaseReminderRoute: SparePartPurchaseReminderRoute,
  SparePartRequestPartRoute: SparePartRequestPartRoute,
  SparePartStockTransactionRoute: SparePartStockTransactionRoute,
  WorkOrderIdRoute: WorkOrderIdRoute,
  WorkOrderAddRoute: WorkOrderAddRoute,
  DocumentationIndexRoute: DocumentationIndexRoute,
  WorkOrderIndexRoute: WorkOrderIndexRoute,
  MasterDataDepartmentIdRoute: MasterDataDepartmentIdRoute,
  MasterDataDepartmentNewRoute: MasterDataDepartmentNewRoute,
  MasterDataMachineIdRoute: MasterDataMachineIdRoute,
  MasterDataMachineNewRoute: MasterDataMachineNewRoute,
  MasterDataSparepartIdRoute: MasterDataSparepartIdRoute,
  MasterDataSparepartNewRoute: MasterDataSparepartNewRoute,
  SparePartOrderRequestIdRoute: SparePartOrderRequestIdRoute,
  SparePartOrderRequestCreateSorRoute: SparePartOrderRequestCreateSorRoute,
  SparePartOrderRequestEditRoute: SparePartOrderRequestEditRoute,
  SparePartRequestOrderListIdRoute: SparePartRequestOrderListIdRoute,
  SparePartRequestOrderListNewRoute: SparePartRequestOrderListNewRoute,
  DocumentationMachineIdIndexRoute: DocumentationMachineIdIndexRoute,
  MasterDataDepartmentIndexRoute: MasterDataDepartmentIndexRoute,
  MasterDataMachineIndexRoute: MasterDataMachineIndexRoute,
  MasterDataSparepartIndexRoute: MasterDataSparepartIndexRoute,
  SparePartOrderRequestIndexRoute: SparePartOrderRequestIndexRoute,
  SparePartRequestOrderListIndexRoute: SparePartRequestOrderListIndexRoute,
  DocumentationMachineIdHistoryHistoryIdRoute:
    DocumentationMachineIdHistoryHistoryIdRoute,
  MasterDataSparepartWarehouseNewRoute: MasterDataSparepartWarehouseNewRoute,
  DocumentationMachineIdHistoryIndexRoute:
    DocumentationMachineIdHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
