/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAnalyticsRouteImport } from './routes/ai-analytics'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as WorkOrderRouteImport } from './routes/work-order'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalyticsRoute = AiAnalyticsRouteImport.update({
  id: '/ai-analytics',
  path: '/ai-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrderRoute = WorkOrderRouteImport.update({
  id: '/work-order',
  path: '/work-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analytics': typeof AiAnalyticsRoute
  '/checklist': typeof ChecklistRoute
  '/documentation': typeof DocumentationRoute
  '/schedule': typeof ScheduleRoute
  '/work-order': typeof WorkOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analytics': typeof AiAnalyticsRoute
  '/checklist': typeof ChecklistRoute
  '/documentation': typeof DocumentationRoute
  '/schedule': typeof ScheduleRoute
  '/work-order': typeof WorkOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analytics': typeof AiAnalyticsRoute
  '/checklist': typeof ChecklistRoute
  '/documentation': typeof DocumentationRoute
  '/schedule': typeof ScheduleRoute
  '/work-order': typeof WorkOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analytics'
    | '/checklist'
    | '/documentation'
    | '/schedule'
    | '/work-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analytics'
    | '/checklist'
    | '/documentation'
    | '/schedule'
    | '/work-order'
  id:
    | '__root__'
    | '/'
    | '/ai-analytics'
    | '/checklist'
    | '/documentation'
    | '/schedule'
    | '/work-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalyticsRoute: typeof AiAnalyticsRoute
  ChecklistRoute: typeof ChecklistRoute
  DocumentationRoute: typeof DocumentationRoute
  ScheduleRoute: typeof ScheduleRoute
  WorkOrderRoute: typeof WorkOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analytics': {
      id: '/ai-analytics'
      path: '/ai-analytics'
      fullPath: '/ai-analytics'
      preLoaderRoute: typeof AiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-order': {
      id: '/work-order'
      path: '/work-order'
      fullPath: '/work-order'
      preLoaderRoute: typeof WorkOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalyticsRoute: AiAnalyticsRoute,
  ChecklistRoute: ChecklistRoute,
  DocumentationRoute: DocumentationRoute,
  ScheduleRoute: ScheduleRoute,
  WorkOrderRoute: WorkOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
